<?php
// Redis CacheKey
const ALL_USER = 'ALL_USER';
const USER_ID = 'USER_ID_';

const ALL_TOUR = 'ALL_TOUR';
const TOUR_ID = 'TOUR_ID_';
const TOUR_SLUG = 'TOUR_SLUG_';
const TOUR_ACTIVE = 'TOUR_ACTIVE';
const TOUR_INACTIVE = 'TOUR_INACTIVE';
const ALL_TOUR_REQUIRE = 'ALL_TOUR_REQUIRE';
const TOUR_REQUIRE_ID = 'TOUR_REQUIRE_ID_';
const ALL_BOOKING_TOUR = 'ALL_BOOKING_TOUR';
const BOOKING_TOUR_ID = 'BOOKING_TOUR_ID_';
const ALL_NEWS = 'ALL_NEWS';
const NEWS_ID = 'NEWS_ID_';
const NEWS_SLUG = 'NEWS_SLUG_';