<?php
// Redis CacheKey
const ALL_USER = 'ALL_USER';
const USER_ID = 'USER_ID_';

const ALL_TOUR = 'ALL_TOUR';
const TOUR_ID = 'TOUR_ID_';
const TOUR_SLUG = 'TOUR_SLUG_';
const TOUR_ACTIVE = 'TOUR_ACTIVE';
const TOUR_INACTIVE = 'TOUR_INACTIVE';
const ALL_TOUR_REQUIRE = 'ALL_TOUR_REQUIRE';
const TOUR_REQUIRE_ID = 'TOUR_REQUIRE_ID_';